### ISSUE TITLE
Sharezone CLI uses `dart test` even when `flutter_test` is a dependency

### ISSUE THREAD

**Issue by nilsreichardt** [SharezoneApp/sharezone-app#474]
In our current branch for the migration of the `holidays` package, we have  the `flutter` package not as direct dependency. For testing we are using the `flutter_test` package. Because we don't have `flutter` not as direct package, the Sharezone CLI tries to run `dart test` instead of `flutter test`. 

This is the pubspec.yaml
```yaml
dependencies:
  built_collection: ^5.1.0
  built_value: ^8.1.1
  key_value_store:
    path: ../key_value_store
  cloud_functions: ^4.0.11
  app_functions:
    path: ../app_functions

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.7
  build_runner: ^2.1.4
  built_value_generator: ^8.1.1
  lints: ^2.0.1
```

This result into this issue:

```
Exception: Process ended with non-zero exit code: fvm dart test (exit code 65): 

 stdout:Could not find package `test` or file `test:test`
You need to add a dev_dependency on package:test.
Try running `dart pub add --dev test`.
```
